export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_NAME="GET_PRODUCT_NAME";
export const FILTER_BY_BRAND='FILTER_BY_BRAND';
export const FILTER_BY_CATEGORY='FILTER_BY_CATEGORY';
export const FILTER_BY_SIZE='FILTER_BY_SIZE';
export const FILTER_BY_PRICE='FILTER_BY_PRICE';